version: "3"

services:
  database:
    container_name: jiraiya-database
    image: postgres:14
    environment:
        POSTGRES_USER: ${DATABASE_USER:-admin}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
        POSTGRES_DB: jiraiya
    restart: unless-stopped
    ports:
        - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - ./.database-data:/var/lib/postgresql/data
    networks:
      - network

  core:
    container_name: jiraiya-backend-core
    depends_on:
      - database
    build:
      context: ./backend/core
    restart: unless-stopped
    ports:
      - "${BACKEND_CORE_PORT:-8080}:8080"
    env_file:
      - .env
    networks:
      - network

  client:
    container_name: jiraiya-frontend-dashboard
    depends_on:
      - core
    restart: unless-stopped
    build:
      context: ./frontend/dashboard
    ports:
      - "${FRONTEND_DASHBOARD_PORT:-4173}:4173"
    networks:
      - network

volumes:
  database-data:
networks:
  network:
    driver: bridge